site:
  title: Redpanda Docs
  start_page: redpanda:get-started:intro-to-events.adoc
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: https://github.com/JakeSCahill/redpanda-docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    tabs-sync-option: true
  extensions:
  - '@asciidoctor/tabs'